spring:
  application:
    name: Gerenciado de Produtos
  datasource:
    url: jdbc:postgresql://localhost:5439/gerenciador_de_produtos
    diver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    test-while-idle: true
    validation-query: "SELECT 1"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
      naming:
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl"
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        properties:
            hibernate:
              dialect: "org.hibernate.dialect.PostgreSQLDialect"

security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 86400000

